### GET ALL
GET http://localhost:3000/users

### GET
GET http://localhost:3000/users/14

### POST
### Inserts/Creates one new user
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Bryce Jones",
  "username": "bjones",
  "email": "bjones.biz",
  "address": {
    "street": "Moxy Trail",
    "suite": "Suite 280",
    "city": "Howbout",
    "zipcode": "58804-1099",
    "geo": {
      "lat": "24.8918",
      "lng": "21.8984"
    }
  },
  "phone": "210.067.6132",
  "website": "jonesinc.io",
  "company": {
    "name": "Flayer Group",
    "catchPhrase": "Configurable multimedia task-force",
    "bs": "generate enterprise e-tailers"
  }
}

###PUT 
### Updates one user
PUT http://localhost:3000/users/14
Content-Type: application/json

{
  "name": "James Earl Jones",
  "username": "jjones",
  "email": "cflayer.biz",
  "address": {
    "street": "Moxy Trail",
    "suite": "Suite 280",
    "city": "Howbout",
    "zipcode": "58804-1099",
    "geo": {
      "lat": "24.8918",
      "lng": "21.8984"
    }
  },
  "phone": "210.067.6132",
  "website": "flayergroup.io",
  "company": {
    "name": "Flayer Group",
    "catchPhrase": "Configurable multimedia task-force",
    "bs": "generate enterprise e-tailers"
  }
}

### DELETE
### DELETES one user
DELETE http://localhost:3000/users/14