  ### Delete
  DELETE http://localhost:3000/courses/17

### INSERT
POST http://localhost:3000/courses/
Content-Type:  application/json

{
    "dept": "CompSci",
    "courseNum": 101,
    "courseName": "Intro to React",
    "instructor": "Craig",
    "startDate": "April 9",
    "numDays": 3
  }


